services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: alexandre
      POSTGRES_PASSWORD: NumSey_123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - 'postgre-network'
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks:
  postgre-network:
