services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379" # Porta padrão do Redis
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"] # Configuração para persistência de dados

volumes:
  redis_data:
    driver: local
